### ISSUE TITLE
Sysinfo not loading

### ISSUE THREAD

**Issue by MayhemBill** [Wyn10/Wyn-RedV3Cogs#6]
Whenever I try to load sysinfo it says `this package could not be loaded for the following reasons: sysinfo` and nothing in console

**Comment by Wyn10** [comment]
@MayhemBill What does the traceback command say?  Did also you look in red.log?

**Comment by MayhemBill** [comment]
Traceback says no exception has occurred yet, and nothing in logs either.

I've tried to restart the bot and I have even removed cog/repo and reinstalled and nothing worked.

**Comment by Wyn10** [comment]
@MayhemBill I've been told it's a red bug that's fixed on dev branch.  If you can update to dev.

**Comment by MayhemBill** [comment]
Alright, I'll look into it

**Comment by MayhemBill** [comment]
Okay so this isn't an issue with red bot, the issue was with my system, for some reason, it was installing both 3.6 and 3.7 of python, and it would run the bot off 3.7, and most of the cogs would be fine with python libs installed on 3.6, but psutil wouldn't work that way

**Comment by JGriffin34432** [comment]
I'm having the same issue as well.

**Comment by MayhemBill** [comment]
Make sure you're installing psutil to the same version of python the bot is running on
